[package]
name = "tui-renderer"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
crossterm = "0.28.1"
unicode-box-builder = { git = "https://github.com/valyntyler/unicode-box-builder.git" }
